#include <string.h>
#include "../mnn.h"

int main() {
    /*AUTOGENERATED MODEL START*/

    /* Layer 0: 2 Inputs → 4 Outputs */
    float w0[] = {-0.0887384, -0.10049188, -0.68383735, -0.68383515, -0.38707536, -0.38707694, 0.0008813123, -0.24189658};
    float b0[] = {-8.805089e-06, 12.309684, 3.8707964, -0.012114938};

    /* Layer 1: 4 Inputs → 4 Outputs */
    float w1[] = {0.14923543, 0.38670257, 2.0808842, 0.096015394, 0.034262896, -0.12487455, 0.47424096, -0.09325403, -0.15977919, 0.008215047, 1.2053796, -0.21132891, -0.039263558, -0.8773593, -0.22186464, -0.033052698};
    float b1[] = {-2.1148076, -0.2985375, -0.004737055, 4.799756};

    /* Layer 2: 4 Inputs → 1 Outputs */
    float w2[] = {-0.8183656, 0.49182102, -0.26351047, 1.6643449};
    float b2[] = {10.011329};

    MicroNeuralNetwork mnn = {0};
    mnn.num_layers = 3;

    mnn.layers[0].input_size = 2;
    mnn.layers[0].output_size = 4;
    memcpy(mnn.layers[0].weights, w0, sizeof(w0));
    memcpy(mnn.layers[0].biases, b0, sizeof(b0));

    mnn.layers[1].input_size = 4;
    mnn.layers[1].output_size = 4;
    memcpy(mnn.layers[1].weights, w1, sizeof(w1));
    memcpy(mnn.layers[1].biases, b1, sizeof(b1));

    mnn.layers[2].input_size = 4;
    mnn.layers[2].output_size = 1;
    memcpy(mnn.layers[2].weights, w2, sizeof(w2));
    memcpy(mnn.layers[2].biases, b2, sizeof(b2));

    /*AUTOGENERATED MODEL END*/

    printf("Model memory size: %f MB\n", get_model_memory_size(&mnn));

    float test_input[] = {1.0f, 4.0f};
    float *out = inference(&mnn, test_input);

    printf("Output: %f\n", out[0]);
    /* no free() – inference uses a static buffer */
}